/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef InstrumentManager_CONSTANTS_H
#define InstrumentManager_CONSTANTS_H

#include "InstrumentManager_types.h"

namespace Interface { namespace Wqimc { namespace Api { namespace Manager {

class InstrumentManagerConstants {
 public:
  InstrumentManagerConstants();

};

extern const InstrumentManagerConstants g_InstrumentManager_constants;

}}}} // namespace

#endif
