/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "InstrumentManager_constants.h"

namespace Interface { namespace Wqimc { namespace Api { namespace Manager {

const InstrumentManagerConstants g_InstrumentManager_constants;

InstrumentManagerConstants::InstrumentManagerConstants() {
}

}}}} // namespace

