/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef InstrumentAgent_CONSTANTS_H
#define InstrumentAgent_CONSTANTS_H

#include "InstrumentAgent_types.h"

namespace Interface { namespace Wqimc { namespace Api { namespace Agent {

class InstrumentAgentConstants {
 public:
  InstrumentAgentConstants();

};

extern const InstrumentAgentConstants g_InstrumentAgent_constants;

}}}} // namespace

#endif
