/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "InstrumentAgent_constants.h"

namespace Interface { namespace Wqimc { namespace Api { namespace Agent {

const InstrumentAgentConstants g_InstrumentAgent_constants;

InstrumentAgentConstants::InstrumentAgentConstants() {
}

}}}} // namespace

